### PR TITLE
BaseDish refactored, MainDish extends BaseDish

### PR DESCRIPTION
**Pull request by ArinaJur**
Created fields and constructor in BaseDish, MainDish extends BaseDish

### CODE REVIEW

**Review by mishinaolia — APPROVED** [review]

**Review by NYerlan — APPROVED** [review]

**Review by zorganpro — APPROVED** [review]

**Review by IrinaBehrend — APPROVED** [review]

**Review by Remsy2 — APPROVED** [review]
LGFM!

**Review by Staschampion — APPROVED** [review]
GOOD JOB

**Review by ghost — APPROVED** [review]
LGFM

**Review by LenaDik — APPROVED** [review]
LGFM

**Review by IrinaRiz — APPROVED** [review]
well done

**Review by Aleksandr-Belski — APPROVED** [review]
Looks good for me

**Review by yasyaG — APPROVED** [review]
Good Job

**Review by RichardGob — COMMENTED** [review]
LGFM

**Review by viktoria-anatsko — COMMENTED** [review]
LGFM

**Review by OlgaKogut — COMMENTED** [review]
LGFM

**Pull request merged**
